[package]
name = "Vendor_MarketPlace"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
hyper = "1.6.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.2", features = ["full", "rt"] }
tower = "0.5.2"
tower-http = "0.6.2"
